export const cities = [
  {
    key: '基隆市',
    value: '基隆市',
  },
  {
    key: '臺北市',
    value: '臺北市',
  },
  {
    key: '新北市',
    value: '新北市',
  },
  {
    key: '桃園市',
    value: '桃園市',
  },
  {
    key: '新竹市',
    value: '新竹市',
  },
  {
    key: '新竹縣',
    value: '新竹縣',
  },
  {
    key: '苗栗縣',
    value: '苗栗縣',
  },
  {
    key: '臺中市',
    value: '臺中市',
  },
  {
    key: '彰化縣',
    value: '彰化縣',
  },
  {
    key: '南投縣',
    value: '南投縣',
  },
  {
    key: '雲林縣',
    value: '雲林縣',
  },
  {
    key: '嘉義市',
    value: '嘉義市',
  },
  {
    key: '嘉義縣',
    value: '嘉義縣',
  },
  {
    key: '臺南市',
    value: '臺南市',
  },
  {
    key: '高雄市',
    value: '高雄市',
  },
  {
    key: '屏東縣',
    value: '屏東縣',
  },
  {
    key: '臺東縣',
    value: '臺東縣',
  },
  {
    key: '花蓮縣',
    value: '花蓮縣',
  },
  {
    key: '宜蘭縣',
    value: '宜蘭縣',
  },
  {
    key: '澎湖縣',
    value: '澎湖縣',
  },
  {
    key: '金門縣',
    value: '金門縣',
  },
  {
    key: '連江縣',
    value: '連江縣',
  },
]
export const district = {
  基隆市: [
    { key: '仁愛區', value: '仁愛區' },
    { key: '信義區', value: '信義區' },
    { key: '中正區', value: '中正區' },
    { key: '中山區', value: '中山區' },
    { key: '安樂區', value: '安樂區' },
    { key: '暖暖區', value: '暖暖區' },
    { key: '七堵區', value: '七堵區' },
  ],
  臺北市: [
    { key: '中正區', value: '中正區' },
    { key: '大同區', value: '大同區' },
    { key: '中山區', value: '中山區' },
    { key: '松山區', value: '松山區' },
    { key: '大安區', value: '大安區' },
    { key: '萬華區', value: '萬華區' },
    { key: '信義區', value: '信義區' },
    { key: '士林區', value: '士林區' },
    { key: '北投區', value: '北投區' },
    { key: '內湖區', value: '內湖區' },
    { key: '南港區', value: '南港區' },
    { key: '文山區', value: '文山區' },
  ],
  新北市: [
    { key: '萬里區', value: '萬里區' },
    { key: '金山區', value: '金山區' },
    { key: '板橋區', value: '板橋區' },
    { key: '汐止區', value: '汐止區' },
    { key: '深坑區', value: '深坑區' },
    { key: '石碇區', value: '石碇區' },
    { key: '瑞芳區', value: '瑞芳區' },
    { key: '平溪區', value: '平溪區' },
    { key: '雙溪區', value: '雙溪區' },
    { key: '貢寮區', value: '貢寮區' },
    { key: '新店區', value: '新店區' },
    { key: '坪林區', value: '坪林區' },
    { key: '烏來區', value: '烏來區' },
    { key: '永和區', value: '永和區' },
    { key: '中和區', value: '中和區' },
    { key: '土城區', value: '土城區' },
    { key: '三峽區', value: '三峽區' },
    { key: '樹林區', value: '樹林區' },
    { key: '鶯歌區', value: '鶯歌區' },
    { key: '三重區', value: '三重區' },
    { key: '新莊區', value: '新莊區' },
    { key: '泰山區', value: '泰山區' },
    { key: '林口區', value: '林口區' },
    { key: '蘆洲區', value: '蘆洲區' },
    { key: '五股區', value: '五股區' },
    { key: '八里區', value: '八里區' },
    { key: '淡水區', value: '淡水區' },
    { key: '三芝區', value: '三芝區' },
    { key: '石門區', value: '石門區' },
  ],
  桃園市: [
    { key: '中壢區', value: '中壢區' },
    { key: '平鎮區', value: '平鎮區' },
    { key: '龍潭區', value: '龍潭區' },
    { key: '楊梅區', value: '楊梅區' },
    { key: '新屋區', value: '新屋區' },
    { key: '觀音區', value: '觀音區' },
    { key: '桃園區', value: '桃園區' },
    { key: '龜山區', value: '龜山區' },
    { key: '八德區', value: '八德區' },
    { key: '大溪區', value: '大溪區' },
    { key: '復興區', value: '復興區' },
    { key: '大園區', value: '大園區' },
    { key: '蘆竹區', value: '蘆竹區' },
  ],
  新竹市: [
    { key: '東區', value: '東區' },
    { key: '北區', value: '北區' },
    { key: '香山區', value: '香山區' },
  ],
  新竹縣: [
    { key: '竹北市', value: '竹北市' },
    { key: '湖口鄉', value: '湖口鄉' },
    { key: '新豐鄉', value: '新豐鄉' },
    { key: '新埔鎮', value: '新埔鎮' },
    { key: '關西鎮', value: '關西鎮' },
    { key: '芎林鄉', value: '芎林鄉' },
    { key: '寶山鄉', value: '寶山鄉' },
    { key: '竹東鎮', value: '竹東鎮' },
    { key: '五峰鄉', value: '五峰鄉' },
    { key: '橫山鄉', value: '橫山鄉' },
    { key: '尖山鄉', value: '尖山鄉' },
    { key: '北埔鄉', value: '北埔鄉' },
    { key: '峨眉鄉', value: '峨眉鄉' },
  ],
  苗栗縣: [
    { key: '竹南鎮', value: '竹南鎮' },
    { key: '頭份市', value: '頭份市' },
    { key: '三灣鄉', value: '三灣鄉' },
    { key: '南庄鄉', value: '南庄鄉' },
    { key: '獅潭鄉', value: '獅潭鄉' },
    { key: '後龍鎮', value: '後龍鎮' },
    { key: '通霄鎮', value: '通霄鎮' },
    { key: '苑裡鎮', value: '苑裡鎮' },
    { key: '苗栗市', value: '苗栗市' },
    { key: '造橋鄉', value: '造橋鄉' },
    { key: '頭屋鄉', value: '頭屋鄉' },
    { key: '公館鄉', value: '公館鄉' },
    { key: '大湖鄉', value: '大湖鄉' },
    { key: '泰安鄉', value: '泰安鄉' },
    { key: '銅鑼鄉', value: '銅鑼鄉' },
    { key: '三義鄉', value: '三義鄉' },
    { key: '西湖鄉', value: '西湖鄉' },
    { key: '卓蘭鎮', value: '卓蘭鎮' },
  ],
  臺中市: [
    { key: '中區', value: '中區' },
    { key: '東區', value: '東區' },
    { key: '南區', value: '南區' },
    { key: '西區', value: '西區' },
    { key: '北區', value: '北區' },
    { key: '北屯區', value: '北屯區' },
    { key: '西屯區', value: '西屯區' },
    { key: '南屯區', value: '南屯區' },
    { key: '太平區', value: '太平區' },
    { key: '大里區', value: '大里區' },
    { key: '霧峰區', value: '霧峰區' },
    { key: '烏日區', value: '烏日區' },
    { key: '豐原區', value: '豐原區' },
    { key: '后里區', value: '后里區' },
    { key: '石崗區', value: '石崗區' },
    { key: '東勢區', value: '東勢區' },
    { key: '和平區', value: '和平區' },
    { key: '新社區', value: '新社區' },
    { key: '潭子區', value: '潭子區' },
    { key: '大雅區', value: '大雅區' },
    { key: '神岡區', value: '神岡區' },
    { key: '大肚區', value: '大肚區' },
    { key: '沙鹿區', value: '沙鹿區' },
    { key: '龍井區', value: '龍井區' },
    { key: '梧棲區', value: '梧棲區' },
    { key: '清水區', value: '清水區' },
    { key: '大甲區', value: '大甲區' },
    { key: '外埔區', value: '外埔區' },
    { key: '大安區', value: '大安區' },
  ],
  彰化縣: [
    { key: '彰化市', value: '彰化市' },
    { key: '芬園鄉', value: '芬園鄉' },
    { key: '花壇鄉', value: '花壇鄉' },
    { key: '秀水鄉', value: '秀水鄉' },
    { key: '鹿港鎮', value: '鹿港鎮' },
    { key: '福興鄉', value: '福興鄉' },
    { key: '綠西鄉', value: '綠西鄉' },
    { key: '和美鎮', value: '和美鎮' },
    { key: '伸港鄉', value: '伸港鄉' },
    { key: '員林市', value: '員林市' },
    { key: '社頭鄉', value: '社頭鄉' },
    { key: '永靖鄉', value: '永靖鄉' },
    { key: '埔心鄉', value: '埔心鄉' },
    { key: '溪湖鎮', value: '溪湖鎮' },
    { key: '大村鄉', value: '大村鄉' },
    { key: '埔鹽鄉', value: '埔鹽鄉' },
    { key: '田中鎮', value: '田中鎮' },
    { key: '北斗鎮', value: '北斗鎮' },
    { key: '田尾鄉', value: '田尾鄉' },
    { key: '埤頭鄉', value: '埤頭鄉' },
    { key: '溪洲鄉', value: '溪洲鄉' },
    { key: '竹塘鄉', value: '竹塘鄉' },
    { key: '二林鎮', value: '二林鎮' },
    { key: '大城鄉', value: '大城鄉' },
    { key: '芳苑鄉', value: '芳苑鄉' },
    { key: '二水鄉', value: '二水鄉' },
  ],
  南投縣: [
    { key: '南投市', value: '南投市' },
    { key: '中寮鄉', value: '中寮鄉' },
    { key: '草屯鎮', value: '草屯鎮' },
    { key: '國姓鄉', value: '國姓鄉' },
    { key: '埔里鎮', value: '埔里鎮' },
    { key: '仁愛鄉', value: '仁愛鄉' },
    { key: '名間鄉', value: '名間鄉' },
    { key: '集集鎮', value: '集集鎮' },
    { key: '水里鄉', value: '水里鄉' },
    { key: '魚池鄉', value: '魚池鄉' },
    { key: '信義鄉', value: '信義鄉' },
    { key: '竹山鎮', value: '竹山鎮' },
    { key: '鹿谷鄉', value: '鹿谷鄉' },
  ],
  雲林縣: [
    { key: '斗南鎮', value: '斗南鎮' },
    { key: '大埤鄉', value: '大埤鄉' },
    { key: '虎尾鎮', value: '虎尾鎮' },
    { key: '土庫鎮', value: '土庫鎮' },
    { key: '褒忠鄉', value: '褒忠鄉' },
    { key: '東勢鄉', value: '東勢鄉' },
    { key: '臺西鄉', value: '臺西鄉' },
    { key: '崙背鄉', value: '崙背鄉' },
    { key: '麥寮鄉', value: '麥寮鄉' },
    { key: '斗六市', value: '斗六市' },
    { key: '林內鄉', value: '林內鄉' },
    { key: '古坑鄉', value: '古坑鄉' },
    { key: '莿桐鄉', value: '莿桐鄉' },
    { key: '西螺鎮', value: '西螺鎮' },
    { key: '二崙鄉', value: '二崙鄉' },
    { key: '北港鎮', value: '北港鎮' },
    { key: '水林鄉', value: '水林鄉' },
    { key: '口湖鄉', value: '口湖鄉' },
    { key: '四湖鄉', value: '四湖鄉' },
    { key: '元長鄉', value: '元長鄉' },
  ],
  嘉義市: [
    { key: '東區', value: '東區' },
    { key: '西區', value: '西區' },
  ],
  嘉義縣: [
    { key: '番路鄉', value: '番路鄉' },
    { key: '梅山鄉', value: '梅山鄉' },
    { key: '竹崎鄉', value: '竹崎鄉' },
    { key: '阿里山鄉', value: '阿里山鄉' },
    { key: '中埔鄉', value: '中埔鄉' },
    { key: '大埔鄉', value: '大埔鄉' },
    { key: '水上鄉', value: '水上鄉' },
    { key: '鹿草鄉', value: '鹿草鄉' },
    { key: '太保市', value: '太保市' },
    { key: '朴子市', value: '朴子市' },
    { key: '東石鄉', value: '東石鄉' },
    { key: '六腳鄉', value: '六腳鄉' },
    { key: '新港鄉', value: '新港鄉' },
    { key: '民雄鄉', value: '民雄鄉' },
    { key: '大林鎮', value: '大林鎮' },
    { key: '溪口鄉', value: '溪口鄉' },
    { key: '義竹鄉', value: '義竹鄉' },
    { key: '布袋鎮', value: '布袋鎮' },
  ],
  臺南市: [
    { key: '中西區', value: '中西區' },
    { key: '東區', value: '東區' },
    { key: '南區', value: '南區' },
    { key: '北區', value: '北區' },
    { key: '安平區', value: '安平區' },
    { key: '安南區', value: '安南區' },
    { key: '永康區', value: '永康區' },
    { key: '歸仁區', value: '歸仁區' },
    { key: '新化區', value: '新化區' },
    { key: '左鎮區', value: '左鎮區' },
    { key: '玉井區', value: '玉井區' },
    { key: '楠西區', value: '楠西區' },
    { key: '南化區', value: '南化區' },
    { key: '仁德區', value: '仁德區' },
    { key: '關廟區', value: '關廟區' },
    { key: '龍崎區', value: '龍崎區' },
    { key: '官田區', value: '官田區' },
    { key: '麻豆區', value: '麻豆區' },
    { key: '佳里區', value: '佳里區' },
    { key: '西港區', value: '西港區' },
    { key: '七股區', value: '七股區' },
    { key: '將軍區', value: '將軍區' },
    { key: '學甲區', value: '學甲區' },
    { key: '北門區', value: '北門區' },
    { key: '新營區', value: '新營區' },
    { key: '後壁區', value: '後壁區' },
    { key: '白河區', value: '白河區' },
    { key: '東山區', value: '東山區' },
    { key: '六甲區', value: '六甲區' },
    { key: '下營區', value: '下營區' },
    { key: '柳營區', value: '柳營區' },
    { key: '鹽水區', value: '鹽水區' },
    { key: '善化區', value: '善化區' },
    { key: '大內區', value: '大內區' },
    { key: '山上區', value: '山上區' },
    { key: '新市區', value: '新市區' },
    { key: '安定區', value: '安定區' },
  ],
  高雄市: [
    { key: '新興區', value: '新興區' },
    { key: '前金區', value: '前金區' },
    { key: '苓雅區', value: '苓雅區' },
    { key: '鹽埕區', value: '鹽埕區' },
    { key: '鼓山區', value: '鼓山區' },
    { key: '旗津區', value: '旗津區' },
    { key: '前鎮區', value: '前鎮區' },
    { key: '三民區', value: '三民區' },
    { key: '楠梓區', value: '楠梓區' },
    { key: '小港區', value: '小港區' },
    { key: '左營區', value: '左營區' },
    { key: '仁武區', value: '仁武區' },
    { key: '大社區', value: '大社區' },
    { key: '東沙群島', value: '東沙群島' },
    { key: '南沙群島', value: '南沙群島' },
    { key: '岡山區', value: '岡山區' },
    { key: '路竹區', value: '路竹區' },
    { key: '阿蓮區', value: '阿蓮區' },
    { key: '田寮區', value: '田寮區' },
    { key: '燕巢區', value: '燕巢區' },
    { key: '橋頭區', value: '橋頭區' },
    { key: '梓官區', value: '梓官區' },
    { key: '彌陀區', value: '彌陀區' },
    { key: '永安區', value: '永安區' },
    { key: '湖內區', value: '湖內區' },
    { key: '鳳山區', value: '鳳山區' },
    { key: '大寮區', value: '大寮區' },
    { key: '林園區', value: '林園區' },
    { key: '鳥松區', value: '鳥松區' },
    { key: '大樹區', value: '大樹區' },
    { key: '旗山區', value: '旗山區' },
    { key: '美濃區', value: '美濃區' },
    { key: '六龜區', value: '六龜區' },
    { key: '內門區', value: '內門區' },
    { key: '杉林區', value: '杉林區' },
    { key: '甲仙區', value: '甲仙區' },
    { key: '桃源區', value: '桃源區' },
    { key: '那瑪夏區', value: '那瑪夏區' },
    { key: '茂林區', value: '茂林區' },
    { key: '茄萣區', value: '茄萣區' },
  ],
  屏東縣: [
    { key: '屏東市', value: '屏東市' },
    { key: '三地門鄉', value: '三地門鄉' },
    { key: '霧臺鄉', value: '霧臺鄉' },
    { key: '瑪家鄉', value: '瑪家鄉' },
    { key: '九如鄉', value: '九如鄉' },
    { key: '里港鄉', value: '里港鄉' },
    { key: '高樹鄉', value: '高樹鄉' },
    { key: '鹽埔鄉', value: '鹽埔鄉' },
    { key: '長治鄉', value: '長治鄉' },
    { key: '麟洛鄉', value: '麟洛鄉' },
    { key: '竹田鄉', value: '竹田鄉' },
    { key: '內埔鄉', value: '內埔鄉' },
    { key: '萬丹鄉', value: '萬丹鄉' },
    { key: '潮州鎮', value: '潮州鎮' },
    { key: '泰武鄉', value: '泰武鄉' },
    { key: '來義鄉', value: '來義鄉' },
    { key: '萬巒鄉', value: '萬巒鄉' },
    { key: '崁頂鄉', value: '崁頂鄉' },
    { key: '新埤鄉', value: '新埤鄉' },
    { key: '南州鄉', value: '南州鄉' },
    { key: '林邊鄉', value: '林邊鄉' },
    { key: '東港鎮', value: '東港鎮' },
    { key: '琉球鄉', value: '琉球鄉' },
    { key: '佳冬鄉', value: '佳冬鄉' },
    { key: '新園鄉', value: '新園鄉' },
    { key: '枋寮鄉', value: '枋寮鄉' },
    { key: '枋山鄉', value: '枋山鄉' },
    { key: '春日鄉', value: '春日鄉' },
    { key: '獅子鄉', value: '獅子鄉' },
    { key: '車城鄉', value: '車城鄉' },
    { key: '牡丹鄉', value: '牡丹鄉' },
    { key: '恆春鎮', value: '恆春鎮' },
    { key: '滿州鄉', value: '滿州鄉' },
  ],
  臺東縣: [
    { key: '臺東市', value: '臺東市' },
    { key: '綠島鄉', value: '綠島鄉' },
    { key: '蘭嶼鄉', value: '蘭嶼鄉' },
    { key: '延平鄉', value: '延平鄉' },
    { key: '卑南鄉', value: '卑南鄉' },
    { key: '鹿野鄉', value: '鹿野鄉' },
    { key: '關山鎮', value: '關山鎮' },
    { key: '海端鄉', value: '海端鄉' },
    { key: '池上鄉', value: '池上鄉' },
    { key: '東河鄉', value: '東河鄉' },
    { key: '成功鎮', value: '成功鎮' },
    { key: '長濱鄉', value: '長濱鄉' },
    { key: '太麻里鄉', value: '太麻里鄉' },
    { key: '金鋒鄉', value: '金鋒鄉' },
    { key: '大武鄉', value: '大武鄉' },
    { key: '達仁鄉', value: '達仁鄉' },
  ],
  花蓮縣: [
    { key: '花蓮市', value: '花蓮市' },
    { key: '新城鄉', value: '新城鄉' },
    { key: '秀林鄉', value: '秀林鄉' },
    { key: '吉安鄉', value: '吉安鄉' },
    { key: '壽豐鄉', value: '壽豐鄉' },
    { key: '鳳林鎮', value: '鳳林鎮' },
    { key: '光復鄉', value: '光復鄉' },
    { key: '豐濱鄉', value: '豐濱鄉' },
    { key: '瑞穗鄉', value: '瑞穗鄉' },
    { key: '萬榮鄉', value: '萬榮鄉' },
    { key: '玉里鎮', value: '玉里鎮' },
    { key: '卓溪鄉', value: '卓溪鄉' },
    { key: '富里鄉', value: '富里鄉' },
  ],
  宜蘭縣: [
    { key: '宜蘭市', value: '宜蘭市' },
    { key: '頭城鎮', value: '頭城鎮' },
    { key: '礁溪鄉', value: '礁溪鄉' },
    { key: '壯圍鄉', value: '壯圍鄉' },
    { key: '員山鄉', value: '員山鄉' },
    { key: '羅東鎮', value: '羅東鎮' },
    { key: '三星鄉', value: '三星鄉' },
    { key: '大同鄉', value: '大同鄉' },
    { key: '五結鄉', value: '五結鄉' },
    { key: '冬山鄉', value: '冬山鄉' },
    { key: '蘇澳鎮', value: '蘇澳鎮' },
    { key: '南澳鄉', value: '南澳鄉' },
  ],
  澎湖縣: [
    { key: '馬公市', value: '馬公市' },
    { key: '西嶼鄉', value: '西嶼鄉' },
    { key: '望安鄉', value: '望安鄉' },
    { key: '七美鄉', value: '七美鄉' },
    { key: '白沙鄉', value: '白沙鄉' },
    { key: '湖西鄉', value: '湖西鄉' },
  ],
  金門縣: [
    { key: '金沙鎮', value: '金沙鎮' },
    { key: '金湖鎮', value: '金湖鎮' },
    { key: '金寧鄉', value: '金寧鄉' },
    { key: '金城鎮', value: '金城鎮' },
    { key: '烈嶼鄉', value: '烈嶼鄉' },
    { key: '烏坵鄉', value: '烏坵鄉' },
  ],
  連江縣: [
    { key: '南竿鄉', value: '南竿鄉' },
    { key: '北竿鄉', value: '北竿鄉' },
    { key: '莒光鄉', value: '莒光鄉' },
    { key: '東引鄉', value: '東引鄉' },
  ],
}
